// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
// import Navbar from '@/components/navbar'
// const inter = Inter({ subsets: ['latin'] })
// import ImageSlider from'@/components/LogoSlider'
// import Link from 'next/link'
// import Footer2 from '@/components/footer2'
// import Footer from '@/components/footer'


// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        
//         <link rel="icon" href="/favicon.ico" />
//         <link rel="preconnect" href="https://fonts.googleapis.com"/>
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
//         <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"/>

//       </Head>
//       <main className=''>
//         <div className='home_section2 mainscr'>
       
//         <Navbar></Navbar>
//         <section className="section">


//     <div className="home_text">
//       <div>
//       <h2 className='home_text_st'>Access creative <br/>and original designs from talented worldwide</h2>

//       </div>
//       <div> 
//       <form className="sr-div2">
//                 <input type="text" name='' placeholder="Logo, Brand identity, Backaging..." />
//                 <select name="test">
//                   <option value="CONTESTPROJECT">CONTEST PROJECT</option>
                  
//                 </select>
//                 <input type="submit" name=''  value="Start" /> 
//             </form>
//             </div>
//     </div>
//     <div className='home_img'>
//     <img
//       src="/home1.png"
//       alt="Image"
//       className="image"/>
//     </div>
   
    
//      <div className='home-h'>
//   <h1 className='home-h1 home-su'>IP PROTECTION FOR YOUR DESIGNS - 100% GUARANTEE</h1>
//   </div>
//   </section>
     
//         </div>
        
//         <section className=' mainscr'>
//         <h1 className='next_text_st'>Popular Categories:</h1>
//         <ImageSlider></ImageSlider>
//         <div className='part'>
//         <button className='btn1'>Get Started</button>
//         </div>
//         </section>
//         <section className=' mainscr'>
//           <div className='part'>
//           <h1 className='home-h1 fs50'>How it works & Experience</h1>
//           </div>
 

//         </section>
      
   
//       <Footer2/>
    
//       <Footer></Footer>
//       </main>
//     </>
//   )
// }
